{
  "formatVersion": "1.1",
  "component": {
    "group": "me.hacket",
    "module": "Modularization2",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "Modularization2-1.0.0.aar",
          "url": "Modularization2-1.0.0.aar",
          "size": 33262,
          "sha512": "8a50af3d79e22f965a206e2d8260f83f23a0a1176e3878e59003e5a3be57ae9ee3fcabe0168326fbc1db9f400a2da62df0d93839cc56d7c4bf6c4c61b7f38b94",
          "sha256": "ad93b957e3a41666ed8c80391aa0421b44dcf93e71cd49598af2db597879cafd",
          "sha1": "c8190dc67dea7a78c92441968b4c35a98c8e9384",
          "md5": "9b6783e7caa5b6d758e3afb7bd838157"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "me.hacket",
          "module": "Modularization1",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "Modularization2-1.0.0.aar",
          "url": "Modularization2-1.0.0.aar",
          "size": 33262,
          "sha512": "8a50af3d79e22f965a206e2d8260f83f23a0a1176e3878e59003e5a3be57ae9ee3fcabe0168326fbc1db9f400a2da62df0d93839cc56d7c4bf6c4c61b7f38b94",
          "sha256": "ad93b957e3a41666ed8c80391aa0421b44dcf93e71cd49598af2db597879cafd",
          "sha1": "c8190dc67dea7a78c92441968b4c35a98c8e9384",
          "md5": "9b6783e7caa5b6d758e3afb7bd838157"
        }
      ]
    }
  ]
}
