{
  "formatVersion": "1.1",
  "component": {
    "group": "me.hacket",
    "module": "Modularization1",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "Modularization1-1.0.0.aar",
          "url": "Modularization1-1.0.0.aar",
          "size": 33261,
          "sha512": "a3f87e4ae616b66539a406caa0158d25f1e26ae08a57cbdf2f27c01baa40b078a94f09dff704fe440fdbf52ed0045da181a8815fa30b8fe66e408099825a4cbf",
          "sha256": "83afd3664fa19aa9d4876affee2cf2887d6d34c801a0248c93ca196c9556df32",
          "sha1": "29775732a449856efc25118886311aa0218bad3b",
          "md5": "8ed2966de9ce191dc8f35720269b2a2a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "Modularization1-1.0.0.aar",
          "url": "Modularization1-1.0.0.aar",
          "size": 33261,
          "sha512": "a3f87e4ae616b66539a406caa0158d25f1e26ae08a57cbdf2f27c01baa40b078a94f09dff704fe440fdbf52ed0045da181a8815fa30b8fe66e408099825a4cbf",
          "sha256": "83afd3664fa19aa9d4876affee2cf2887d6d34c801a0248c93ca196c9556df32",
          "sha1": "29775732a449856efc25118886311aa0218bad3b",
          "md5": "8ed2966de9ce191dc8f35720269b2a2a"
        }
      ]
    }
  ]
}
